<a href="https://colab.research.google.com/github/veager/VeNote-Natural-language-processing/blob/main/tutorials/02_%E8%AF%8D%E9%A2%91%E7%BB%9F%E8%AE%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. 词频与逆向文件频率 tf-idf

### 1.1 `scikit-learn` 库

#### 1.1.1 统计词频 tf

`CountVectorizer` 类

In [ ]:
# 语料，4 个文档
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(analyzer='word')   # stop_words='english' 设置 stop words
word_cnt = vectorizer.fit_transform(corpus)     # 统计 词频，返回 sparse matrix 类型
word_cnt = word_cnt.toarray()

# 输出
print(vectorizer.get_feature_names_out())
print(word_cnt)

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
# 字符统计
vectorizer1 = CountVectorizer(analyzer='char')
word_cnt1 = vectorizer.fit_transform(corpus)

# 输出
print(vectorizer.get_feature_names_out())
print(word_cnt1.toarray())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
# n 元模型
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
word_cnt2 = vectorizer2.fit_transform(corpus)

# 输出
print(vectorizer2.get_feature_names_out())
print(word_cnt2.toarray())

['and this' 'document is' 'first document' 'is the' 'is this'
 'second document' 'the first' 'the second' 'the third' 'third one'
 'this document' 'this is' 'this the']
[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]


利用 `TfidfTransformer` 类，设置 use_idf=False，统计归一化的词频 tf

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

# 只统计归一化的 tf, 设置 use_idf=False
tf_norm = TfidfTransformer(use_idf=False, smooth_idf=True).fit_transform(word_cnt)
print(tf_norm.toarray())

print(word_cnt / np.linalg.norm(word_cnt, ord=2, axis=1, keepdims=True))

[[0.         0.4472136  0.4472136  0.4472136  0.         0.
  0.4472136  0.         0.4472136 ]
 [0.         0.70710678 0.         0.35355339 0.         0.35355339
  0.35355339 0.         0.35355339]
 [0.40824829 0.         0.         0.40824829 0.40824829 0.
  0.40824829 0.40824829 0.40824829]
 [0.         0.4472136  0.4472136  0.4472136  0.         0.
  0.4472136  0.         0.4472136 ]]
[[0.         0.4472136  0.4472136  0.4472136  0.         0.
  0.4472136  0.         0.4472136 ]
 [0.         0.70710678 0.         0.35355339 0.         0.35355339
  0.35355339 0.         0.35355339]
 [0.40824829 0.         0.         0.40824829 0.40824829 0.
  0.40824829 0.40824829 0.40824829]
 [0.         0.4472136  0.4472136  0.4472136  0.         0.
  0.4472136  0.         0.4472136 ]]


#### 1.1.2 统计 idf

计算 `tf-idf` 的对象 `TfidfTransformer`，经过拟合后，可以获得 `.idf_` 属性

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

word_cnt = [[3, 0, 1], [2, 0, 0], [3, 0, 0], [4, 0, 0], [3, 2, 0], [3, 0, 2]]
# 6 个文档，每个文档有 3 个词

transformer = TfidfTransformer(smooth_idf=True)
transformer.fit_transform(word_cnt)

print(transformer.idf_)
print(transformer.n_features_in_)

[1.         2.25276297 1.84729786]
3


#### 1.1.3 统计 tf-idf

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

word_cnt = [[3, 0, 1], [2, 0, 0], [3, 0, 0], [4, 0, 0], [3, 2, 0], [3, 0, 2]]
# 6 个文档，每个文档有 3 个词

transformer = TfidfTransformer(smooth_idf=True)
# 参数: norm='l2',
#       use_idf=True, 设所有 idf=1, 即计算归一化的词频
#       smooth_idf=True, 是否对 idf 的计算公式平滑

# 输入为 统计的词频
tfidf = transformer.fit_transform(word_cnt)  # 返回稀疏矩阵
print(tfidf.toarray())

[[0.85151335 0.         0.52433293]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [0.55422893 0.83236428 0.        ]
 [0.63035731 0.         0.77630514]]


### 1.2 `NLTK` 库

In [ ]:
from nltk.text import TextCollection
from nltk.tokenize import word_tokenize

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]


texts = TextCollection(corpus)

for d, doc in enumerate(corpus):
    # 分词
    tokens = word_tokenize(doc)
    # 过滤停词
    tokens = [w for w in tokens if w not in ['.', '?']]

    print('document {0}'.format(d+1))
    # for each word
    for w, word in enumerate(tokens):
        tf = texts.tf(word, doc)
        idf = texts.idf(word)
        tf_idf = texts.tf_idf(word, doc)

        print('{0:10}'.format(word), end=' ')
        print('{0:<8.4f}'.format(tf), end=' ')
        print('{0:<8.4f}'.format(idf), end=' ')
        print('{0:<8.4f}'.format(tf_idf), end=' ')
        print()


from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

vectorizer = CountVectorizer(analyzer='word')   # stop_words='english' 设置 stop words
word_cnt = vectorizer.fit_transform(corpus)     # 统计 词频

transformer = TfidfTransformer(smooth_idf=True)
tf_idf = transformer.fit_transform(word_cnt)

print(vectorizer.get_feature_names_out())
print(np.round(tf_idf.toarray(), 4))    # tf-idf
print(np.round(transformer.idf_, 4))    # idf

document 1
This       0.0370   0.6931   0.0257   
is         0.0741   0.0000   0.0000   
the        0.0370   0.0000   0.0000   
first      0.0370   0.6931   0.0257   
document   0.0370   0.2877   0.0107   
document 2
This       0.0270   0.6931   0.0187   
document   0.0541   0.2877   0.0156   
is         0.0541   0.0000   0.0000   
the        0.0270   0.0000   0.0000   
second     0.0270   1.3863   0.0375   
document   0.0541   0.2877   0.0156   
document 3
And        0.0385   1.3863   0.0533   
this       0.0385   0.6931   0.0267   
is         0.0769   0.0000   0.0000   
the        0.0385   0.0000   0.0000   
third      0.0385   1.3863   0.0533   
one        0.0385   1.3863   0.0533   
document 4
Is         0.0370   1.3863   0.0513   
this       0.0370   0.6931   0.0257   
the        0.0370   0.0000   0.0000   
first      0.0370   0.6931   0.0257   
document   0.0370   0.2877   0.0107   
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0.     0.4698 0.5803 0.3841 